### ISSUE TITLE
No way to delete mods once they are installed

### ISSUE THREAD

**Issue by fearofshorts** [Artentus/ModMyFactory2#17]
Just noticed that there doesn't seem to be a way to remove mods from the mod pane once you have installed them. I'd just like to request this fix.

**Comment by Artentus** [comment]
I am aware, I have not yet implemented this because I am unsure how to handle this.  
There are two possible options:  
1. When deleting a mod all versions of that mod is deleted and the mod is removed from the manager or
2. only the selected version is deleted and if there are more versions installed the mod will remain in the manager.

1. Is more straight-forward but 2. allows for finer control.

**Comment by fearofshorts** [comment]
Could I suggest just a dialogue box asking the user which of the two they'd prefer? Or you could add it as an advanced option in settings.

**Comment by Artentus** [comment]
Settings are definitelly my preferred way. I think throwing lots of dialog boxes at users does not make for a great experience.

**Comment by Artentus** [comment]
Mods can be deleted now
