### ISSUE TITLE
Better Mac Support

### ISSUE THREAD

**Issue by pyrox0** [Artentus/ModMyFactory2#35]
I'm mrhedgehog0 on the Factorio Forums, and I am here to answer as many mac-specific questions as I can. Please note that I am not a .NET dev, so I can't tell you about quirks on .NET on mac.

**Comment by ModdedGamers** [comment]
Now, when I download factorio, it simply fails, not crashing, but not succeeding either. No errors are generated, so I have no logs to share.

**Comment by Artentus** [comment]
Thank you for your help.  
I learned that the 3rd party decompression library I'm using does not support the DMG format at all. That's why it still doesn't work. I've spent the last 3 days implementing it myself but it turns out DMG is a pretty complex format so it'll take at least a couple more days until we can try yet again.

**Comment by ModdedGamers** [comment]
Alright! Sounds great, happy to test!

**Comment by Artentus** [comment]
I have submitted my Dmg implementation to the author of the 3rd party library I'm using. Now we just have to wait until it gets added into a stable release before we can continue.

**Comment by pyrox0** [comment]
closed as I no longer use a mac
