### ISSUE TITLE
Issue when using a Steam Library on a separate disk to install games in

### ISSUE THREAD

**Issue by BlueWeabo** [Artentus/ModMyFactory2#44]
Recently I had gotten a new SSD and decided to move all my games to it, but steam wasn't installed on it so it made a "SteamLibrary" folder where it put the games. Factorio was there and I was trying to figure out how to make MMF detect Factorio from the new folder, as it was no longer in the C drive. Reinstalling MMF did nothing, changing some settings did nothing. Decided to reinstall steam in the new drive and it worked. It seems like MMF only tries to detect the base "Steam" folder and not any "SteamLibrary" folders anywhere else.

**Comment by Artentus** [comment]
Not true, MMF will try to find all library folders on your system.

On Windows MMF will first look up "HKLM\SOFTWARE\Valve\Steam\InstallPath" in the registery to find the Steam install path.
On Linux MMF will assume Steam is installed in "$home\.steam".

Then it will read "steamapps/libraryfolders.vdf" inside the Steam installation folder to get a list of all Steam libraries on the system. It will then search all libraries for Factorio installations.

I've had Factorio installed on a different harddrive from the beginning of development and it has always worked for me.  
So your issue must be somewhere else.

**Comment by BlueWeabo** [comment]
Alright. I will try to find the issue and what could cause it then. Thank you for the answer!

**Comment by Artentus** [comment]
I have some new information on this. I just opened MMF for the first time since then and look at that, it didn't work for me either anymore.  
It appears at some point during the last months Steam changed their library file format in a way that broke MMFs auto-detection. It is possible you received this update before me and experienced the issue while I was not able to reproduce it because it didn't exist on my machine yet.

Anyway, it was an easy fix. Update will be live shortly.
