### ISSUE TITLE
Application not opening GUI

### ISSUE THREAD

**Issue by szentigrad3** [Artentus/ModMyFactory2#47]
so i added all my mods and created a modpack and then closed it, next time i opened it shows its open in the taskbar but no GUI.
[ModMyFactoryGUI.zip](https://github.com/Artentus/ModMyFactory2/files/7969547/ModMyFactoryGUI.zip)

**Comment by Ethrel** [comment]
So, I just had this happen myself. Don't have logs or details, but in my settings file (%appdata%/ModMyFactoryGUI/settings.json) the "window_restore_state" value was "-32000;-32000;160;39"

That seems to be, from some pure guess-work, window location x and y, and a width and height. Changed both -32000 values to 0, opened the program, and the window showed up in the top left of my screen (at what I expected 0,0 to be), with just enough window space to show the logo, minimize, and close buttons. Resized it, and bam! Window is back.

Something somewhere is saving a bad value into the config, shoving the window fairly far off top the top left of the screen.

Hopefully this helps.

**Comment by Artentus** [comment]
I have previously tried to identify why this is happening but couldn't find any apparent reason.  
Since I haven't worked at all on MMF for almost a year I'm now gonna try the sledghammer method and simply filter positions of -32000,-32000 out. That way at last the window won't be hidden offscreen, although it will reset the previously saved location.
