### ISSUE TITLE
Program crashes on startup

### ISSUE THREAD

**Issue by sthorsten** [Artentus/ModMyFactory2#7]
Hey, I really liked ModMyFactory and wanted to give the new version a shot.
Unfortunately the program immediately crashes after a second or two and giving me "An unkown server error occurred" message in the logs (which I attached).

- [log_20200817.txt](https://github.com/Artentus/ModMyFactory2/files/5084845/log_20200817.txt)

Maybe you look into that. Thanks in advance :)
~ThorsHero | Thorsten

**Comment by Artentus** [comment]
I'm getting the same error as of today, it is caused by the web API throwing a 500 Internal Server Error.. It looks like the Factorio servers are having some issues, probably due to the 1.0 release, aand cannot process large requests anymore.

It is, however, a bug that MMF hard crashes because of this. It's supposed to simply display an error message. I will look into this.

**Comment by sthorsten** [comment]
Alright, I'll keep an eye on that and try again later.
Thank you for the quick response.

**Comment by Artentus** [comment]
Hotfix is out
