### ISSUE TITLE
How use in Windows?

### ISSUE THREAD

**Issue by GeekinaCave** [Artentus/ModMyFactory2#8]
Good Day

i been using the ModMyFactory 1.X for a long time, is a great tool for multiple mod-plays of Factorio. but for some reason this new version doesn't work for me, when i try to use ModMyFactoryGUI.exe nothing happens, no interface, no error, no nothing. then i check the Appdata, and in the log says for some reason that he shutdown himself ¿?. Maybe i need a prerequisite, a core.Net or something like that?
Windows 10 2004

[log_20200816.txt](https://github.com/Artentus/ModMyFactory2/files/5085439/log_20200816.txt)

**Comment by Artentus** [comment]
Are you using the standalone or the normal Windows version?
You can also try to enable verbose logging (-v command line argument) and see if something new shows up in the log.
And I have just released a hotfix for a very common startup crash, try running that first.

**Comment by GeekinaCave** [comment]
Okay, i cleanup the appdata folder of the app, download and execute the standalone version (which assume is the portable one), then execute the ModMyFactoryGUI -v from cmd 2 times and still nothing, this is the new log:

[log_20200817.txt](https://github.com/Artentus/ModMyFactory2/files/5086093/log_20200817.txt)

**Comment by mobius1qwe** [comment]
from your log data seems that the new MMF is trying to launch Steam version of factorio but your system doesn't have it, it has one of the other versions instead(GOG or website standalone) and by trying to launch the steam version (which you don't have) it's throwing an error (AV possibly?)

**Comment by GeekinaCave** [comment]
yes i use website standalone factorio, how I configure that to the ModMyFactory2?

**Comment by mobius1qwe** [comment]
I think this is something that Artentus will develop in the upcomming weeks, MMF2 is still in early alpha access so it will have a few bugs here and there, You can use MMF1 in the meantime as it's working for me at least.

**Comment by GeekinaCave** [comment]
Ok thanks 👍

**Comment by Artentus** [comment]
The issue is actually not related to the Factorio Steam version, that line just means it has not been found on your system.
Also standalone only means no runtime is required on your system, it's not any more portable. I will release portable versions once I reach beta. Since you're running on the latest Windows 10 version I recommend you try the normal Windows release instead.

Just based on the logs there is no actual information that would let me immediately see what's going wrong. The application seems to load normally and then simply shuts down without error. It's certainly possible it's related to the standalone version, according to Microsoft the packing is still a beta feature, but I'll have to do more investigating to say for certain.

**Comment by GeekinaCave** [comment]
well tried also the normal windows release and have the same effect, its just with MMF1 even with the non portable version it could open the interface and allow you to download factorio directly, that's why it seems so weird for me that MMF2 doesn't.
I test it in my desk pc ryzen 5 1600 and my laptop ryzen 5 3500U both with clean install of W10 2004, does somebody else with AMD has tested it? 🤔

**Comment by Artentus** [comment]
MMF2 uses a very different GUI framework to enable cross-platform compatibility so you cannot really compare the two.

I've just compiled a new build with even more logging, hopefully this will reveal the issue:
[mmf-debug.zip](https://github.com/Artentus/ModMyFactory2/files/5087942/mmf-debug.zip)

**Comment by GeekinaCave** [comment]
OK...
I cleanup the \AppData\Roaming\ModMyFactoryGUI
put the build you send me in C:\mmf-debug
i open a CMD inside and execute ModMyFactoryGUI -v
this is what i get in the log:

[log_20200818.txt](https://github.com/Artentus/ModMyFactory2/files/5092598/log_20200818.txt)

it looks that is missing something from the route D:\Visual Studio Projekte\ModMyFactory2\ModMyFactoryGUI\*.* which doesn't exist in my PC because y reserve D:\ for my USB's.

**Comment by mobius1qwe** [comment]
@Artentus I probably should stop trying to help, I don't understand C# very well but seems to me that the model: FactorioViewModel doesn't have a method called FirstOrDefault() and its throwing an error when you initialize it.

Before this line, on line 143 you're trying to get which instance is being selected, I'm thinking this is on regards of if its steam, GOG or website. but since its TryGet it will either return something or null. So your FactorioViewModel.Instances is null and it doesn't enter the if condition, so it goes into the next if condition, on line 157 where its throwing the NullPointerException error because on the line just above, 156, you're trying to call the method FirstOrDefault() from a null object. So the mainviewmodel hangs and doesn't continue the loading process, throwing the unable to initialize GUI framework, then on the App.xaml.cs I think that the next Log(GUI framework sucessfuly initialized) should be on an "else" part of the try-catch, as it's saving the log saying it was loaded.

Then it tries to run  base.OnFrameworkInitializationCompleted(); with a NullPointer on the mainwindow and it crashes

**Comment by GeekinaCave** [comment]
what version of .NET Framework should have installed?

**Comment by mobius1qwe** [comment]
Try installing the latest one, I have them all because I develop applications too so I'm not sure which one you need.

**Comment by Artentus** [comment]
Based on that log I think I've finally figured it out.

MMF is not trying to access anything on D:, those are just debug symbols.
There was indeed a pretty dumb bug causing a null reference exception on fresh installs, but that wasn't the main issue either.

As it turns out there is a broken mod on the portal. This mod does not have any releases associated with it which is causing the crash. Funnily enough if you try to access this particular mod on the actual mod portal the server also throws an error.

So someone has either intentionally or unintentionally, created an invalid mod on the portal. Congratulations to that person.

**Comment by Artentus** [comment]
Just released a patch, hopefully this will resolve your issues

**Comment by GeekinaCave** [comment]
i just repeat the steps with v2.1.3.9 and success!

![imagen](https://user-images.githubusercontent.com/8534866/90686719-61c81980-e231-11ea-91c9-70738219be99.png)

Thanks!
